<?php

return[
    'products' => [
        [
          'name'=>'RELAXED FIT TEE UNISEX',
          'brand'=>"Levi's",
          'price'=>'14,99 €',
          'priceOld'=>'29,99 €',
          'img'=>'1.webp',
          'imgHover'=>'1b.webp',
          'discount'=>'-50%',
          'green'=>'Sostenibilità',
          'favorite'=>false,
        ],
        [
          'name'=>'ROSES TEE',
          'brand'=>"Guess",
          'price'=>'20,99 € ',
          'priceOld'=>'29,99 €',
          'img'=>'2.webp',
          'imgHover'=>"2b.webp",
          'discount'=>'-30%',
          'green'=>null,
          'favorite'=>false,
        ],
        [
          'name'=>'VOGLIA DI COLORI PASTELLO',
          'brand'=>"Come Zucchero Filato",
          'price'=>'129,99 €',
          'priceOld'=>'184,99 €',
          'img'=>'3.webp',
          'imgHover'=>'3b.webp',
          'discount'=>'-30%',
          'green'=>null,
          'favorite'=>false,
        ],
        [
          'name'=>'TEE UNISEX',
          'brand'=>"Levi's",
          'price'=>'14,99 €',
          'priceOld'=>'29,99 €',
          'img'=>'4.webp',
          'imgHover'=>'4b.webp',
          'discount'=>'-50%',
          'green'=>'Sostenibilità',
          'favorite'=>false,
        ],
        [
          'name'=>'STRIPE BODICE',
          'brand'=>"Maya Deluxe",
          'price'=>'99,99 €',
          'priceOld'=>null,
          'img'=>'5.webp',
          'imgHover'=>'5b.webp',
          'discount'=>null,
          'green'=>null,
          'favorite'=>false,
        ],
        [
          'name'=>'MAGLIONE - BLACK',
          'brand'=>"Esprit",
          'price'=>'29,99 €',
          'priceOld'=>null,
          'img'=>'6.webp',
          'imgHover'=>'6b.webp',
          'discount'=>null,
          'green'=>'Sostenibilità',
          'favorite'=>false,
        ],
    ],
];
