<?php

return[
    'products' => [
        [
          'name'=>'RELAXED FIT TEE UNISEX',
          'brand'=>"Levi's",
          'price'=>'14,99 €',
          'priceOld'=>'29,99 €',
          'img'=>'1.webp',
          'imgHover'=>'1b.webp',
          'discount'=>'-50%',
          'green'=>'Sostenibilità',
          'favorite'=>false,
          'slug'=> 'levis-relaxed-fit-tee-unisex',
          'gender' => 'man',
          'description' => 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellendus veniam minus, aliquam ab repudiandae explicabo voluptas non at obcaecati fugiat maiores commodi illo dolorem eligendi. Necessitatibus quibusdam explicabo adipisci laborum accusantium facilis inventore iste? Illo necessitatibus delectus quae ipsum!',
        ],
        [
          'name'=>'ROSES TEE',
          'brand'=>"Guess",
          'price'=>'20,99 € ',
          'priceOld'=>'29,99 €',
          'img'=>'2.webp',
          'imgHover'=>"2b.webp",
          'discount'=>'-30%',
          'green'=>null,
          'favorite'=>true,
          'slug' => 'guess-roses-tee',
          'gender' => 'woman',
          'description' => 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellendus veniam minus, aliquam ab repudiandae explicabo voluptas non at obcaecati fugiat maiores commodi illo dolorem eligendi. Necessitatibus quibusdam explicabo adipisci laborum accusantium facilis inventore iste? Illo necessitatibus delectus quae ipsum!',
        ],
        [
          'name'=>'VOGLIA DI COLORI PASTELLO',
          'brand'=>"Come Zucchero Filato",
          'price'=>'129,99 €',
          'priceOld'=>'184,99 €',
          'img'=>'3.webp',
          'imgHover'=>'3b.webp',
          'discount'=>'-30%',
          'green'=>null,
          'favorite'=>false,
          'slug' => 'come-zucchero-filato-voglia-di-colori-pastello',
          'gender' => 'woman',
          'description' => 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellendus veniam minus, aliquam ab repudiandae explicabo voluptas non at obcaecati fugiat maiores commodi illo dolorem eligendi. Necessitatibus quibusdam explicabo adipisci laborum accusantium facilis inventore iste? Illo necessitatibus delectus quae ipsum!',
        ],
        [
          'name'=>'TEE UNISEX',
          'brand'=>"Levi's",
          'price'=>'14,99 €',
          'priceOld'=>'29,99 €',
          'img'=>'4.webp',
          'imgHover'=>'4b.webp',
          'discount'=>'-50%',
          'green'=>'Sostenibilità',
          'favorite'=>true,
          'slug' => 'levis-tee-unisex',
          'gender' => 'man',
          'description' => 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellendus veniam minus, aliquam ab repudiandae explicabo voluptas non at obcaecati fugiat maiores commodi illo dolorem eligendi. Necessitatibus quibusdam explicabo adipisci laborum accusantium facilis inventore iste? Illo necessitatibus delectus quae ipsum!',
        ],
        [
          'name'=>'STRIPE BODICE',
          'brand'=>"Maya Deluxe",
          'price'=>'99,99 €',
          'priceOld'=>null,
          'img'=>'5.webp',
          'imgHover'=>'5b.webp',
          'discount'=>null,
          'green'=>null,
          'favorite'=>false,
          'slug' => 'maya-deluxe-stripe-bodice',
          'gender' => 'woman',
          'description' => 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellendus veniam minus, aliquam ab repudiandae explicabo voluptas non at obcaecati fugiat maiores commodi illo dolorem eligendi. Necessitatibus quibusdam explicabo adipisci laborum accusantium facilis inventore iste? Illo necessitatibus delectus quae ipsum!',
        ],
        [
          'name'=>'MAGLIONE - BLACK',
          'brand'=>"Esprit",
          'price'=>'29,99 €',
          'priceOld'=>null,
          'img'=>'6.webp',
          'imgHover'=>'6b.webp',
          'discount'=>null,
          'green'=>'Sostenibilità',
          'favorite'=>false,
          'slug' => 'esprit-maglione-black',
          'gender' => 'woman',
          'description' => 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellendus veniam minus, aliquam ab repudiandae explicabo voluptas non at obcaecati fugiat maiores commodi illo dolorem eligendi. Necessitatibus quibusdam explicabo adipisci laborum accusantium facilis inventore iste? Illo necessitatibus delectus quae ipsum!',
        ],
    ],
];
